//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMsgSrv
{
    public class MPositionServiceRequest : Message
    {
        public const string RosMessageName = "ROS_msg_srv/PositionService";

        public MPosRot input;

        public MPositionServiceRequest()
        {
            this.input = new MPosRot();
        }

        public MPositionServiceRequest(MPosRot input)
        {
            this.input = input;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(input.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.input.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MPositionServiceRequest: " +
            "\ninput: " + input.ToString();
        }
    }
}
