//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.ROSMsgSrv
{
    public class MMoveBaseActionGoal : Message
    {
        public const string RosMessageName = "ROS_msg_srv/MoveBaseActionGoal";

        public MHeader header;
        public Actionlib.MGoalID goal_id;
        public Geometry.MPoseStamped poseStamped;

        public MMoveBaseActionGoal()
        {
            this.header = new MHeader();
            this.goal_id = new Actionlib.MGoalID();
            this.poseStamped = new Geometry.MPoseStamped();
        }

        public MMoveBaseActionGoal(MHeader header, Actionlib.MGoalID goal_id, Geometry.MPoseStamped poseStamped)
        {
            this.header = header;
            this.goal_id = goal_id;
            this.poseStamped = poseStamped;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(goal_id.SerializationStatements());
            listOfSerializations.AddRange(poseStamped.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.goal_id.Deserialize(data, offset);
            offset = this.poseStamped.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MMoveBaseActionGoal: " +
            "\nheader: " + header.ToString() +
            "\ngoal_id: " + goal_id.ToString() +
            "\nposeStamped: " + poseStamped.ToString();
        }
    }
}
